name: {{ cookiecutter.env_name }}

# Conda environment with dev dependencies
channels:
  - conda-forge

dependencies:
  - python={{ cookiecutter.python_version_number }}
  - pip
{%- if cookiecutter.dependency_file == 'environment.yml' %}
  # Dev dependencies (conda-native)
  - ipython
  - nbdime
{%- if cookiecutter.jupyter_kernel_support == 'Yes' %}
  - ipykernel
{%- endif %}
{%- if cookiecutter.docs == 'mkdocs' %}
  - mkdocs
{%- endif %}
{%- if cookiecutter.testing_framework == 'pytest' %}
  - pytest
  - pytest-cov
{%- endif %}
{%- if cookiecutter.linting_and_formatting == 'ruff' %}
  - ruff
{%- elif cookiecutter.linting_and_formatting == 'flake8+black+isort' %}
  - black
  - flake8
  - isort
{%- endif %}
{%- endif %}
